name: action-a
description: "composite run action"

on: [workflow_call]

runs:
  using: "composite"
  steps:
    - name: Run my script
      id: test
      run: |
        echo "alpha_version=0.0.1-alpha22" >> $GITHUB_OUTPUT
