name: action-a

on:
  pull_request:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job-a:
    runs-on: ubuntu-latest
    outputs:
      output-a: ${{ steps.step1.outputs.alpha_version }}
    steps:
      - name: Run my script
        id: step1
        run: |
          echo "alpha_version=0.0.1-alpha22" >> $GITHUB_OUTPUT
